#pragma once
// AUTO-GENERATED by extract_core.py -- do not hand-edit, regenerate.
//
// Narrow API over the FAST-LIO algorithm core. The node includes ONLY this
// header, never common_lib.h / use-ikfom.hpp / IMU_Processing.hpp, so the
// non-inline definitions in those upstream headers stay in one translation
// unit and the link stays clean.
#include <string>
#include <vector>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/point_cloud2.hpp>
#include <sensor_msgs/msg/imu.hpp>

struct CoreParams
{
  double gyr_cov = 0.1, acc_cov = 0.1, b_gyr_cov = 0.0001, b_acc_cov = 0.0001;
  double blind = 0.01, filter_size_surf = 0.5, filter_size_map_min = 0.5;
  double cube_len = 200.0, det_range = 300.0, fov_deg = 180.0;
  int lidar_type = 1, scan_line = 16, time_unit = 2, scan_rate = 10;
  int point_filter_num = 2, max_iteration = 4;
  bool extrinsic_est_en = true, path_en = true;
  bool scan_publish_en = true, dense_publish_en = false;
  std::vector<double> extrinT = {0, 0, 0};
  std::vector<double> extrinR = {1, 0, 0, 0, 1, 0, 0, 0, 1};
};

// out[] = pos(3) vel(3) euler(3) quat(4), valid only when core_step() is true
void core_init(const CoreParams &p);
void core_lidar_pc2(const sensor_msgs::msg::PointCloud2::SharedPtr msg);
void core_imu(const sensor_msgs::msg::Imu::SharedPtr msg);
bool core_step(double stamp_sec, double out[13]);
bool core_map_ready();
int core_effective_features();

// Fill `msg` with the latest scan transformed into the world frame, mirroring
// upstream publish_frame_world() (official ROS2 branch laserMapping.cpp:489-511).
// Returns the point count, or 0 when publishing is disabled or the cloud is
// empty -- callers must skip publish() on 0.
int core_registered_cloud(sensor_msgs::msg::PointCloud2 &msg);
