#!/usr/bin/env python3
"""Extract the FAST-LIO algorithm core from the real upstream ROS1 source,
verbatim, apply ONLY the mechanical ROS1->ROS2 rules documented in
migration_guide.md sections 3 and 6, and expose a narrow API so the ROS2 node
stays the only file that touches rclcpp.

Why one translation unit for the core: use-ikfom.hpp defines get_f/df_dx/df_dw
as non-inline free functions, and common_lib.h / IMU_Processing.hpp likewise
carry definitions. Including them from two .cpp files would produce duplicate
symbols at link time. Upstream is single-TU by design (everything lives in
laserMapping.cpp); splitting it is itself a migration decision, so the split is
done at the .cpp level, not the .hpp level.

The compiler judges whether the documented rules are sufficient. That
measurement is the point of this script.
"""
import io
import re

# Paths default to the layout used during development but are overridable so the
# same script regenerates the core inside a fresh verification workspace:
#     python3 extract_core.py --ros1 <laserMapping.cpp> --out <package dir>
import argparse
_ap = argparse.ArgumentParser(description=__doc__)
_ap.add_argument("--ros1", help="upstream ROS1 laserMapping.cpp")
_ap.add_argument("--out", help="migrated package directory")
_a = _ap.parse_args()
_pkg = _a.out or "/root/t4try_ws/src/fast_lio_ros2"
SRC = _a.ros1 or "/root/fastlio_ros1/src/laserMapping.cpp"
DST = _pkg + "/src/fastlio_core.cpp"
HDR = _pkg + "/include/fastlio_core.h"

lines = io.open(SRC, encoding="utf-8", errors="replace").read().split("\n")


def block(a, b):
    return "\n".join(lines[a - 1:b])


# boundaries located by grep against the real file, not guessed
RANGES = [
    (63, 142, "defines + global algorithm state + kf/Measures/p_pre/p_imu"),
    (166, 199, "pointBodyToWorld family"),
    (300, 367, "timediff globals + livox_pcl_cbk + imu_cbk"),
    (368, 424, "sync_packages"),
    (638, 754, "h_share_model"),
]
body = "\n\n".join(block(a, b) for a, b, _ in RANGES)

# ---- documented mechanical rules (migration_guide.md sections 3 / 6) ----
body = re.sub(r"^#include <(?:tf/[a-z_/.]+|eigen_conversions/[a-z_/.]+)>[ \t]*\r?\n",
              "", body, flags=re.M)
# The Livox package was renamed AND re-nospaced between ROS1 and ROS2. This must
# run BEFORE the ConstPtr rules below, otherwise `livox_ros_driver::CustomMsg::
# ConstPtr` is renamed too late to be caught and the compiler emits a
# -Wdeprecated warning about the ROS1-style alias that survives.
body = body.replace("livox_ros_driver::", "livox_ros_driver2::msg::")
body = re.sub(r"\b(sensor_msgs|nav_msgs|geometry_msgs|std_msgs)::([A-Za-z0-9_]+)ConstPtr\b",
              r"\1::msg::\2::ConstSharedPtr", body)
# (?!msg\b) + [A-Z]: without them the engine backtracks "msg" -> "ms" and emits
# sensor_msgs::msg::msg::Imu. Caught by the compiler, not by reading.
body = re.sub(r"\b(sensor_msgs|nav_msgs|geometry_msgs|std_msgs)::(?!msg\b)([A-Z][A-Za-z0-9_]*)(?!::)",
              r"\1::msg::\2", body)
body = re.sub(r"\b(sensor_msgs|nav_msgs|geometry_msgs|std_msgs|livox_ros_driver2)::msg::([A-Za-z0-9_]+)::ConstPtr\b",
              r"\1::msg::\2::ConstSharedPtr", body)
# ROS2 also dropped the non-const ::Ptr alias on generated messages. Scoped to
# the message packages on purpose: pcl::PointCloudXYZI::Ptr is a real typedef
# that must survive, and a bare ::Ptr rule would break it.
body = re.sub(r"\b(sensor_msgs|nav_msgs|geometry_msgs|std_msgs|livox_ros_driver2)::msg::([A-Za-z0-9_]+)::Ptr\b",
              r"\1::msg::\2::SharedPtr", body)
body = re.sub(r"\bfast_lio::([A-Z][A-Za-z0-9_]+)(?!:)", r"fast_lio::msg::\1", body)
# fromSec must be rewritten BEFORE the generic ros::Time substitution, otherwise
# the text is already rclcpp::Time().fromSec( and this rule never matches.
body = body.replace("ros::Time().fromSec(", "rclcpp::Time(0) + rclcpp::Duration::from_seconds(")
body = body.replace("ros::Time", "rclcpp::Time").replace("ros::Publisher", "rclcpp::Publisher")
body = re.sub(r"\bROS_INFO\s*\(", 'RCLCPP_INFO(rclcpp::get_logger("fast_lio"), ', body)
body = re.sub(r"\bROS_WARN\s*\(", 'RCLCPP_WARN(rclcpp::get_logger("fast_lio"), ', body)
body = re.sub(r"\bROS_ERROR\s*\(", 'RCLCPP_ERROR(rclcpp::get_logger("fast_lio"), ', body)
body = re.sub(r"\bROS_ASSERT\s*\(", "assert(", body)
# header.stamp time conversions (section 3.4)
body = body.replace("msg->header.stamp.toSec()", "get_time_sec(msg->header.stamp)")
body = body.replace("msg_in->header.stamp.toSec()", "get_time_sec(msg_in->header.stamp)")
body = body.replace("imu_buffer.front()->header.stamp.toSec()",
                    "get_time_sec(imu_buffer.front()->header.stamp)")
body = body.replace("ros::Time().fromSec(", "rclcpp::Time(0) + rclcpp::Duration::from_seconds(")
# Livox message package renamed between ROS1 and ROS2

HEADER = """#pragma once
// AUTO-GENERATED by extract_core.py -- do not hand-edit, regenerate.
//
// Narrow API over the FAST-LIO algorithm core. The node includes ONLY this
// header, never common_lib.h / use-ikfom.hpp / IMU_Processing.hpp, so the
// non-inline definitions in those upstream headers stay in one translation
// unit and the link stays clean.
#include <string>
#include <vector>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/point_cloud2.hpp>
#include <sensor_msgs/msg/imu.hpp>

struct CoreParams
{
  double gyr_cov = 0.1, acc_cov = 0.1, b_gyr_cov = 0.0001, b_acc_cov = 0.0001;
  double blind = 0.01, filter_size_surf = 0.5, filter_size_map_min = 0.5;
  double cube_len = 200.0, det_range = 300.0, fov_deg = 180.0;
  int lidar_type = 1, scan_line = 16, time_unit = 2, scan_rate = 10;
  int point_filter_num = 2, max_iteration = 4;
  bool extrinsic_est_en = true, path_en = true;
  bool scan_publish_en = true, dense_publish_en = false;
  std::vector<double> extrinT = {0, 0, 0};
  std::vector<double> extrinR = {1, 0, 0, 0, 1, 0, 0, 0, 1};
};

// out[] = pos(3) vel(3) euler(3) quat(4), valid only when core_step() is true
void core_init(const CoreParams &p);
void core_lidar_pc2(const sensor_msgs::msg::PointCloud2::SharedPtr msg);
void core_imu(const sensor_msgs::msg::Imu::SharedPtr msg);
bool core_step(double stamp_sec, double out[13]);
bool core_map_ready();
int core_effective_features();

// Fill `msg` with the latest scan transformed into the world frame, mirroring
// upstream publish_frame_world() (official ROS2 branch laserMapping.cpp:489-511).
// Returns the point count, or 0 when publishing is disabled or the cloud is
// empty -- callers must skip publish() on 0.
int core_registered_cloud(sensor_msgs::msg::PointCloud2 &msg);
"""

PRELUDE = """// AUTO-GENERATED from upstream ROS1 laserMapping.cpp by extract_core.py.
// Algorithm bodies below are verbatim; only the documented mechanical
// ROS1->ROS2 substitutions were applied (migration_guide.md sections 3, 6).
#include "fastlio_core.h"
#include "common_lib.h"
#include "use-ikfom.hpp"
#include "preprocess.h"
#include "ikd-Tree/ikd_Tree.h"
#include "IMU_Processing.hpp"
#include <omp.h>
#include <iostream>
#include <fstream>
#include <thread>
#include <csignal>
#include <chrono>
#include <unistd.h>
#include <algorithm>
#include <iomanip>
#include <pcl/io/pcd_io.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl_conversions/pcl_conversions.h>
#include <nav_msgs/msg/path.hpp>
#include <geometry_msgs/msg/vector3.hpp>

// present in the official ROS2 branch, absent from this ROS1 revision
bool is_first_lidar = true;

static double epsi_local[23] = {0.001};
"""

CALLBACKS = """// PointCloud2 entry point. The ROS1 upstream only had a Livox callback; this
// mirrors the official ROS2 branch's standard_pcl_cbk so the node can consume
// a generic PointCloud2 topic.
static void standard_pcl_cbk(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
    mtx_buffer.lock();
    scan_count++;
    double cur_time = get_time_sec(msg->header.stamp);
    double preprocess_start_time = omp_get_wtime();
    if (!is_first_lidar && cur_time < last_timestamp_lidar)
    {
        std::cerr << "lidar loop back, clear buffer" << std::endl;
        lidar_buffer.clear();
    }
    is_first_lidar = false;
    PointCloudXYZI::Ptr ptr(new PointCloudXYZI());
    p_pre->process(msg, ptr);
    lidar_buffer.push_back(ptr);
    time_buffer.push_back(cur_time);
    last_timestamp_lidar = cur_time;
    s_plot11[scan_count] = omp_get_wtime() - preprocess_start_time;
    mtx_buffer.unlock();
    sig_buffer.notify_all();
}

"""

API = """

/*** narrow API implemented on top of the verbatim core above ***/

void core_init(const CoreParams &p)
{
    p_pre->blind = p.blind;
    p_pre->lidar_type = p.lidar_type;
    p_pre->N_SCANS = p.scan_line;
    p_pre->time_unit = p.time_unit;
    p_pre->SCAN_RATE = p.scan_rate;
    p_pre->point_filter_num = p.point_filter_num;

    gyr_cov = p.gyr_cov; acc_cov = p.acc_cov;
    b_gyr_cov = p.b_gyr_cov; b_acc_cov = p.b_acc_cov;
    filter_size_surf_min = p.filter_size_surf;
    filter_size_map_min = p.filter_size_map_min;
    cube_len = p.cube_len;
    DET_RANGE = p.det_range;
    fov_deg = p.fov_deg;
    NUM_MAX_ITERATIONS = p.max_iteration;
    extrinsic_est_en = p.extrinsic_est_en;
    path_en = p.path_en;
    scan_pub_en = p.scan_publish_en;
    dense_pub_en = p.dense_publish_en;

    Lidar_T_wrt_IMU << p.extrinT[0], p.extrinT[1], p.extrinT[2];
    Lidar_R_wrt_IMU << p.extrinR[0], p.extrinR[1], p.extrinR[2],
                       p.extrinR[3], p.extrinR[4], p.extrinR[5],
                       p.extrinR[6], p.extrinR[7], p.extrinR[8];

    downSizeFilterSurf.setLeafSize(filter_size_surf_min, filter_size_surf_min, filter_size_surf_min);
    downSizeFilterMap.setLeafSize(filter_size_map_min, filter_size_map_min, filter_size_map_min);
    memset(point_selected_surf, true, sizeof(point_selected_surf));
    memset(res_last, -1000.0f, sizeof(res_last));
    // (no set_dimension: KD_TREE is fixed at 3-D by construction)

    p_imu->set_extrinsic(Lidar_T_wrt_IMU, Lidar_R_wrt_IMU);
    p_imu->set_gyr_cov(V3D(gyr_cov, gyr_cov, gyr_cov));
    p_imu->set_acc_cov(V3D(acc_cov, acc_cov, acc_cov));
    p_imu->set_gyr_bias_cov(V3D(b_gyr_cov, b_gyr_cov, b_gyr_cov));
    p_imu->set_acc_bias_cov(V3D(b_acc_cov, b_acc_cov, b_acc_cov));

    fill(epsi_local, epsi_local + 23, 0.001);
    kf.init_dyn_share(get_f, df_dx, df_dw, h_share_model, NUM_MAX_ITERATIONS, epsi_local);
}

void core_lidar_pc2(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
    standard_pcl_cbk(msg);
}

void core_imu(const sensor_msgs::msg::Imu::SharedPtr msg)
{
    imu_cbk(msg);
}

bool core_map_ready()
{
    return ikdtree.Root_Node != nullptr;
}

int core_effective_features()
{
    return effct_feat_num;
}

// verbatim transcription of upstream publish_frame_world(), with the ROS1
// publisher call replaced by a fill-the-message return so the node keeps
// ownership of the rclcpp::Publisher (see migration_guide.md section 3).
int core_registered_cloud(sensor_msgs::msg::PointCloud2 &msg)
{
    if (!scan_pub_en) {
        return 0;
    }

    PointCloudXYZI::Ptr laserCloudFullRes(dense_pub_en ? feats_undistort : feats_down_body);
    int size = laserCloudFullRes->points.size();
    if (size == 0) {
        return 0;
    }
    PointCloudXYZI::Ptr laserCloudWorld(new PointCloudXYZI(size, 1));

    for (int i = 0; i < size; i++)
    {
        pointBodyToWorld(&(laserCloudFullRes->points[i]), &(laserCloudWorld->points[i]));
    }

    pcl::toROSMsg(*laserCloudWorld, msg);
    msg.header.stamp = get_ros_time(lidar_end_time);
    msg.header.frame_id = "camera_init";
    publish_count -= PUBFRAME_PERIOD;
    return size;
}

// one full FAST-LIO scan: sync -> undistort -> downsample -> ESKF -> map update
bool core_step(double stamp_sec, double out[13])
{
    if (!sync_packages(Measures)) {
        return false;
    }

    if (flg_first_scan) {
        first_lidar_time = Measures.lidar_beg_time;
        p_imu->first_lidar_time = first_lidar_time;
        flg_first_scan = false;
        return false;
    }

    p_imu->Process(Measures, kf, feats_undistort);
    state_point = kf.get_x();
    pos_lid = state_point.pos + state_point.rot * state_point.offset_T_L_I;

    if (feats_undistort->empty() || feats_undistort == NULL) {
        RCLCPP_WARN(rclcpp::get_logger("fast_lio"), "No point, skip this scan!\\n");
        return false;
    }

    flg_EKF_inited = (Measures.lidar_beg_time - first_lidar_time) < INIT_TIME ? false : true;

    /*** downsample the feature points in a scan ***/
    downSizeFilterSurf.setInputCloud(feats_undistort);
    downSizeFilterSurf.filter(*feats_down_body);
    feats_down_size = feats_down_body->points.size();

    /*** if the ikd-Tree has not been initialized ***/
    if (ikdtree.Root_Node == nullptr) {
        if (feats_down_size > 5) {
            ikdtree.set_downsample_param(filter_size_map_min);
            feats_down_world->resize(feats_down_size);
            for (int i = 0; i < feats_down_size; i++) {
                pointBodyToWorld(&(feats_down_body->points[i]), &(feats_down_world->points[i]));
            }
            ikdtree.Build(feats_down_world->points);
        }
        return false;
    }

    if (feats_down_size < 5) {
        RCLCPP_WARN(rclcpp::get_logger("fast_lio"), "No point, skip this scan!\\n");
        return false;
    }

    normvec->resize(feats_down_size);
    feats_down_world->resize(feats_down_size);
    Nearest_Points.resize(feats_down_size);

    double solve_H_time = 0;
    kf.update_iterated_dyn_share_modified(LASER_POINT_COV, solve_H_time);

    state_point = kf.get_x();
    euler_cur = SO3ToEuler(state_point.rot);
    pos_lid = state_point.pos + state_point.rot * state_point.offset_T_L_I;

    out[0] = state_point.pos(0); out[1] = state_point.pos(1); out[2] = state_point.pos(2);
    out[3] = state_point.vel(0); out[4] = state_point.vel(1); out[5] = state_point.vel(2);
    out[6] = euler_cur(0); out[7] = euler_cur(1); out[8] = euler_cur(2);
    out[9] = state_point.rot.coeffs()[0];
    out[10] = state_point.rot.coeffs()[1];
    out[11] = state_point.rot.coeffs()[2];
    out[12] = state_point.rot.coeffs()[3];

    /*** push the current scan into the map ***/
    if (flg_EKF_inited) {
        feats_down_world->resize(feats_down_size);
        for (int i = 0; i < feats_down_size; i++) {
            pointBodyToWorld(&(feats_down_body->points[i]), &(feats_down_world->points[i]));
        }
        ikdtree.Add_Points(feats_down_world->points, true);
    }
    return true;
}
"""

io.open(HDR, "w", encoding="utf-8", newline="\n").write(HEADER)
io.open(DST, "w", encoding="utf-8", newline="\n").write(PRELUDE + body + CALLBACKS + API)
print("core bytes", len(body), "api bytes", len(API))